### ISSUE TITLE
uni app可以编译成钉钉小程序么

### ISSUE THREAD

**Issue by ronaldoxzb** [wxw850227/jjjshop#6]

**Comment by wxw850227** [comment]
支持的。
![image](https://user-images.githubusercontent.com/64890325/86561960-65128900-bf94-11ea-8739-0b470072d474.png)

**Comment by ronaldoxzb** [comment]
具体要怎么操作呢 大佬🧍‍♂️

**Comment by wxw850227** [comment]
hbuilder x打包

**Comment by ronaldoxzb** [comment]
感谢
